version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: docker/react-app/Dockerfile
    ports:
      - "3001:3001"

  json-server:
    build:
      context: .
      dockerfile: docker/json-server/Dockerfile
    working_dir: /json-server
    ports:
      - "3000:3000"
